HzCasting.WebApp/Controllers/EventoController.cs
using HzCasting.Domain.Entities;
using HzCasting.Domain.Interfaces.Application;
using HzCasting.Infra.Common;
using HzCasting.WebApp.Controllers.Base;
using HzCasting.WebApp.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HzCasting.WebApp.Controllers
{

    public class EventoController : BaseController
    {
        private readonly IEventoApplication _eventoApplication;
        private readonly EventoViewModel _viewModel;
        private readonly IInviteApplication _inviteApplication;
        public EventoController(IEventoApplication eventoApplication, IInviteApplication inviteApplication)
        {
            _inviteApplication = inviteApplication;
            _eventoApplication = eventoApplication;
            _viewModel = new EventoViewModel();
        }

        public ViewResult Index()
        {
            return View();
        }

        public ViewResult Listar(string titulo, string dataInicio, string dataFim, string realizacao)
        {

            try
            {
                titulo = titulo ?? string.Empty;
                DateTime? dataInicioFiltro = null;
                DateTime? dataFimFiltro = null;
                if (dataInicio != null && dataInicio != string.Empty) dataInicioFiltro = dataInicio.ToDate();
                if (dataFim != null && dataFim != string.Empty) dataFimFiltro = dataFim.ToDate();

                var passado = realizacao == Realizacao.Passado.ToString();
                var futuro = realizacao == Realizacao.Futuro.ToString();

                var dados = _eventoApplication.Listar(titulo, dataInicioFiltro, dataFimFiltro, passado, futuro);
                var eventos = dados.Select(ToEventoViewModel).ToList();
                return View(eventos);


            }
            catch (Exception ex)
            {
                Debug.WriteLine($"Erro: {ex}");
                var eventos = new List<EventoViewModel>();
                return View(eventos);
            }
        }


        public ViewResult Cadastrar()
        {

            CarregarSelects();
            return View();
        }

        public ViewResult NoRadar()
        {
            return View();
        }

        public ViewResult Details(int id)
        {
            var evento = _eventoApplication.Obter(id);

            return View(ToEventoViewModel(evento));
        }

        public ActionResult EventosModelo()
        {
            var userId = User.Identity.GetUserId();

            var roles = ObterRoles();

            var eventos = _inviteApplication.Obter(m => (m.Booking.Modelo.IdUsuario == userId || roles.Contains("admin")) &&
                                                    m.StatusTrackInvite == StatusTrackInviteEnum.Aceito &&
                                                    m.Booking.StatusModeloCastingEnum == StatusModeloCastingEnum.Aprovada)
                                            .Select(m => m.Booking.PerfilFiltro.Casting.Evento)
                                            .Select(ToEventoViewModel);

            return View(eventos);
        }


        [HttpPost]
        public ActionResult Cadastrar(EventoViewModel dadosView)
        {
            try
            {
                UfEnum ufEnum = (UfEnum)Enum.Parse(typeof(UfEnum), dadosView.EstadoEndereco);

                dadosView.UFEndereco = (int)ufEnum;


                if (!ModelState.IsValid)
                {
                    CarregarSelects(null, dadosView.UFEndereco);
                    return View(dadosView);
                }

                var dataInicio = AdicionarHoras(dadosView.HoraInicio, dadosView.DataInicio);
                var dataFim = AdicionarHoras(dadosView.HoraFim, dadosView.DataFim);

                var evento = ToEventoModel(dadosView);

                _eventoApplication.Registrar(evento);

                return RedirectToAction("Listar");
            }
            catch (Exception ex)
            {
                CarregarSelects(null, dadosView.UFEndereco);
                Debug.WriteLine($"Erro: {ex}");
                ModelState.AddModelError("", ex.Message);
                return View(dadosView);
            }
        }


        public ActionResult Editar(Int32 id)
        {
            try
            {
                ViewBag.Id = id;
                var evento = _eventoApplication.Obter(id);
                var eventoViewModel = ToEventoViewModel(evento);
                CarregarSelects(null, eventoViewModel.UFEndereco);
                return View("Cadastrar", eventoViewModel);
            }
            catch (Exception ex)
            {
                Debug.WriteLine($"Erro: {ex}");
                return RedirectToAction("Listar");
            }
        }

        [HttpPost]
        public ActionResult Editar(EventoViewModel evento, Int64 idEvento = 0)
        {
            try
            {
                UfEnum ufEnum = (UfEnum)Enum.Parse(typeof(UfEnum), evento.EstadoEndereco);

                evento.UFEndereco = (int)ufEnum;

                if (!ModelState.IsValid)
                {
                    ViewBag.Id = idEvento;
                    CarregarSelects(null, evento.UFEndereco);
                    SetValidationErrors(ModelState);
                    return View("Cadastrar", evento);

                }

                var eventoModel = ToEventoModel(evento);
                eventoModel.Id = idEvento;
                _eventoApplication.Atualizar(eventoModel);

                return RedirectToAction("Listar");
            }
            catch (Exception ex)
            {
                CarregarSelects(null, evento.UFEndereco);
                Debug.WriteLine($"Erro: {ex}");
                ViewBag.Id = idEvento;
                return View("Cadastrar", evento);
            }
        }

        public RedirectToRouteResult Deletar(Int32 id)
        {
            try
            {

                _eventoApplication.Deletar(id);
                return RedirectToAction("Listar");
            }
            catch (Exception ex)
            {
                Debug.WriteLine($"Erro: {ex}");
                return RedirectToAction("Listar");

            }
        }

        #region Private Methods
        private void CarregarSelects(Evento evento = null, Int32? idUF = null)
        {
            var ufEnum = (UfEnum)((int?)evento?.Endereco?.Cep?.UF ?? idUF ?? 0);
            var uf = default(UfEnum).ToSelectListItem(ufEnum);
            ViewBag.Uf = uf;

        }

        private DateTime AdicionarHoras(string hora, DateTime data)
        {

            var horaReferencia = hora.Split(':');
            var dataReferencia = data
                                            .AddHours(double.Parse(horaReferencia[0]))
                                            .AddMinutes(double.Parse(horaReferencia[1]));

            return dataReferencia;
        }

        private Evento ToEventoModel(EventoViewModel dadosView)
        {

            var dataInicio = AdicionarHoras(dadosView.HoraInicio, dadosView.DataInicio);
            var dataFim = AdicionarHoras(dadosView.HoraFim, dadosView.DataFim);
            var evento = new Evento
            {
                Id = (dadosView.EventoId ?? 0),
                DataFim = dataFim,
                DataInicio = dataInicio,
                Local = dadosView.Local,
                Obs = dadosView.Obs,
                Titulo = dadosView.Titulo,
                Endereco = new Endereco
                {
                    Cep = new Cep
                    {
                        CepNumero = dadosView.CepNumeroEndereco,
                        Bairro = dadosView.BairroEndereco,
                        Cidade = dadosView.CidadeEndereco,
                        Estado = dadosView.EstadoEndereco,
                        Logradouro = dadosView.LogradouroEndereco,
                        UF = (UfEnum)dadosView.UFEndereco
                    },
                    Complemento = dadosView.ComplementoEndereco,
                    Numero = dadosView.NumeroEndereco
                },
                Foto = new Foto
                {
                    Descricao = dadosView.FotoEvento?.FileName,
                    Tipo = dadosView.FotoEvento?.ContentType,
                    ImagemBinario = dadosView.FotoEvento?.GetArrayBytes()

                }
            };
            return evento;
        }

        private EventoViewModel ToEventoViewModel(Evento evento)
        {
            var minuteInicio = evento?.DataInicio.Minute.ToString();
            minuteInicio = minuteInicio.Length == 1 ? minuteInicio + "0" : minuteInicio;

            var minuteFim = evento?.DataFim.Minute.ToString();
            minuteFim = minuteFim.Length == 1 ? minuteFim + "0" : minuteFim;

            var eventoVm = new EventoViewModel
            {
                EventoId = (evento?.Id ?? 0),
                Titulo = evento?.Titulo,
                Local = evento?.Local,
                DataInicio = (evento?.DataInicio ?? DateTime.MinValue),
                DataFim = (evento?.DataFim ?? DateTime.MinValue),
                Obs = evento?.Obs,
                HoraFim = $"{evento?.DataFim.Hour}:{minuteFim}",
                HoraInicio = $"{evento?.DataInicio.Hour}:{minuteInicio}",

                BairroEndereco = evento?.Endereco?.Cep?.Bairro,
                CidadeEndereco = evento?.Endereco?.Cep?.Cidade,
                CepNumeroEndereco = evento?.Endereco?.Cep?.CepNumero,
                ComplementoEndereco = evento?.Endereco?.Complemento,
                EstadoEndereco = evento?.Endereco?.Cep?.Estado,
                LogradouroEndereco = evento?.Endereco?.Cep?.Logradouro,
                NumeroEndereco = evento?.Endereco?.Numero,
                UFEndereco = (int)(evento?.Endereco?.Cep?.UF ?? 0),
                EnderecoId = evento?.Endereco?.Id


            };

            return eventoVm;
        }

HzCasting.WebApp/Views/Shared/LoginBackOfficeLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", required: false)

    <script src="https://use.fontawesome.com/53052d2b92.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body style="background-image: url('../Images/bg_login.jpg'); background-size: 100% 100%; background-attachment: fixed;">
        <!--Page Header-->
    <header class="login-header">
        <a href="#">
            <p class="hidden-xs" onclick="redirect()">Back-Office</p>
        </a>
    </header>
    <!-- Page Content -->
    <div class="container">
        <div class="row">
            @RenderBody()
        </div>
    </div>
        

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/Site/common/util.js"></script>
    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        function redirect() {
            window.location = '/account/login?isbackoffice=false'
        }
    </script>
</body>
</html>

HzCasting.WebApp/Views/Shared/_FormUsuario.cshtml
@model HzCasting.WebApp.Models.UsuarioBase
<div class="form-group col-md-6">
    @Html.LabelFor(m => m.Email, new { @class = "" })
    <span class="text-danger">*</span>
    @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
</div>
<div class="form-group col-md-6">
    @Html.LabelFor(m => m.Cpf, new { @class = "" })
    <span class="text-danger">*</span>
    @Html.TextBoxFor(m => m.Cpf, new { @class = "form-control cpf" })
    @Html.ValidationMessageFor(model => model.Cpf, "", new { @class = "text-danger" })
</div>
<div class="form-group col-md-6">
    @Html.LabelFor(m => m.Password, new { @class = "" })
    <span class="text-danger">*</span>
    @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
</div>
<div class="form-group col-md-6">
    @Html.LabelFor(m => m.ConfirmPassword, new { @class = "" })
    <span class="text-danger">*</span>
    @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
    @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
</div>
@*<div class="form-group">
                 <div class="col-md-offset-2 col-md-10">
                     <input type="submit" value="Cadastrar" class="btn btn-default" />
                 </div>
             </div>*
    </script>*@

@section scripts{
    <script type="text/javascript" src="~/Scripts/Site/modelo/cadastrar.js"></script>
}

HzCasting.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="@CultureHelper.GetCurrentNeutralCulture()">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", required: false)


    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

    <script src="https://use.fontawesome.com/53052d2b92.js"></script>

</head>

@{
    var userId = HttpContext.Current.User.Identity.GetUserId();
    bool agencia;
    bool cliente;
    bool backOffice;
    bool modelo;
    bool erroPerfis = false;
    try
    {
        agencia = Roles.IsUserInRole("Agencia");
        cliente = Roles.IsUserInRole("Cliente");
        backOffice = Roles.IsUserInRole("Admin");
        modelo = Roles.IsUserInRole("Modelo");
    }
    catch
    {
        erroPerfis = true;
        cliente = false;
        modelo = false;
        agencia = false;
        backOffice = true;
    }
}
<body>
    <div id="wrapper">
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        <img src="~/Images/logo_hz_sistema.svg" />
                        @*<!-- @Html.ActionLink("HZCasting", "Listar", "Evento", new { area = "" }, new { @class = "navbar-brand" })-->*@
                    </a>
                </li>

                @if (backOffice)
                {
                    <li class="dropdown">
                        <a class="dropdown-toggle" href="/Evento/Listar">
                            <i><img src="~/Images/ico_evento_menu.svg" /></i>@Resources.Eventos
                        </a>
                    </li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" href="/Cliente/Listar"><i><img src="~/Images/ico_cliente_menu.svg" /></i>@Resources.Cliente</a>
                    </li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" href="/BackOffice/ListarUsuarios"><i><img src="~/Images/ico_cliente_menu.svg" /></i>BackOffice</a>
                    </li>
                }

                @if (backOffice)
                {
                    <li class="dropdown">
                        <a class="dropdown-toggle" href="/Modelo/Listar"><i><img src="~/Images/ico_modelo_menu.svg" /></i>@Resources.Modelo</a>
                        @*<ul class="dropdown-custom dropdown-menu" role="menu" aria-labelledby="dLabel">
                                <li>@Html.ActionLink(Resources.CadastrarModelo, "Cadastrar", "Modelo")</li>
                                <li>@Html.ActionLink(Resources.ListarModelo, "Listar", "Modelo")</li>
                                <li>@Html.ActionLink(Resources.FotosModelo, "Index", "Modelo")</li>
                            </ul>*@
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" href="/Agencia/Listar"><i><img src="~/Images/ico_modelo_menu.svg" /></i>@Resources.Agencia</a>
                        <ul class="dropdown-custom dropdown-menu" role="menu" aria-labelledby="dLabel">
                            <li>@Html.ActionLink(Resources.CadastrarAgencia, "Cadastrar", "Agencia")</li>
                            <li>@Html.ActionLink(Resources.ListarAgencia, "Listar", "Agencia")</li>
                        </ul>
                    </li>
                }

                @if (modelo)
                {
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i><img src="~/Images/ico_modelo_menu.svg" /></i>@Resources.Modelo</a>
                        <ul class="dropdown-custom dropdown-menu" role="menu" aria-labelledby="dLabel">
                            <li>@Html.ActionLink(Resources.Perfil, "Perfil", "Modelo")</li>
                            <li>@Html.ActionLink(Resources.Notificacao, "Notificacao", "Modelo")</li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i><img src="~/Images/ico_modelo_menu.svg" /></i>@Resources.Convites</a>
                        <ul class="dropdown-custom dropdown-menu" role="menu" aria-labelledby="dLabel">
                            <li>@Html.ActionLink(Resources.Pendentes, "Pendentes", "Invite")</li>
                            <li>@Html.ActionLink(Resources.Aceitos, "Aceitos", "Invite")</li>
                            <li>@Html.ActionLink(Resources.Rejeitados, "Rejeitados", "Invite")</li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i><img src="~/Images/ico_modelo_menu.svg" /></i>@Resources.Agenda</a>
                        <ul class="dropdown-custom dropdown-menu" role="menu" aria-labelledby="dLabel">
                            <li>@Html.ActionLink(Resources.Casting, "CastingModelo", "Casting")</li>
                            <li>@Html.ActionLink(Resources.Eventos, "EventosModelo", "Evento")</li>
                        </ul>
                    </li>
                    @*<li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i><img src="~/Images/ico_modelo_menu.svg" /></i>@Resources.Idioma</a>
                            <ul class="dropdown-custom dropdown-menu" role="menu" aria-labelledby="dLabel">
                                <li>@Html.ActionLink(Resources.Portugues, "SetCulture", new { culture = "pt-BR", returnUrl = this.Request.RawUrl }, null)</li>
                                <li>@Html.ActionLink(Resources.Ingles, "SetCulture", new { culture = "en", returnUrl = this.Request.RawUrl }, null)</li>
                            </ul>
                        </li>*@
                }

                @if (cliente || backOffice)
                {
                    <li class="dropdown">
                        @if (cliente)
                        {
                            <a class="dropdown-toggle" href="/Casting/ListarPorCliente"><i><img src="~/Images/ico_modelo_menu.svg" /></i>@Resources.Casting</a>
                        }
                        else
                        {
                            <a class="dropdown-toggle" href="/Casting/Listar"><i><img src="~/Images/ico_modelo_menu.svg" /></i>@Resources.Casting</a>


                        }
                        @if (cliente)
                        {
                            //Meus Castings
                        }

                    </li>
                }


                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i><img src="~/Images/ico_usuario_menu.svg" /></i>@Resources.Usuario</a>
                    <ul class="dropdown-custom dropdown-menu" role="menu" aria-labelledby="dLabel">
                        @Html.Partial("_LoginPartial")
                    </ul>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->
        <!--Page Header-->
        <header class="header">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <a href="#menu-toggle" class="menu-toggle-btn" id="menu-toggle">
                            <i class="fa fa-bars" aria-hidden="true"></i>
                        </a>
                    </div>
                    @{

                        var nome = HzCasting.WebApp.Helpers.ResgateCookie.Nome;
                        var email = HzCasting.WebApp.Helpers.ResgateCookie.Email;
                        var sexo = HzCasting.WebApp.Helpers.ResgateCookie.Sexo;
                        String informativo = "";

                        switch (sexo)
                        {
                            case "Masculino":
                                informativo = ", seja bem-vindo";
                                break;
                            case "Feminino":
                                informativo = ", seja bem-vinda";
                                break;
                            default:
                                informativo = ", seja bem-vindo(a)";
                                break;
                        }

                        <ul class="nav navbar-nav navbar-right pull-right menu-right">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    <span class="hidden-xs">@String.Concat(" " + nome, informativo)</span>
                                    <i class="fa fa-chevron-down" aria-hidden="true"></i>
                                </a>
                                <ul class="dropdown-menu">
                                    @*<li><a href="#">Perfil</a></li>*@
                                    <li>@Html.ActionLink(Resources.Portugues, "SetCulture", new { culture = "pt-BR", returnUrl = this.Request.RawUrl }, null)</li>
                                    <li>@Html.ActionLink(Resources.Ingles, "SetCulture", new { culture = "en", returnUrl = this.Request.RawUrl }, null)</li>
                                    @*<li><a href="#"></i>Logout</a></li>*@
                                    <li>@Html.ActionLink("Logout", "LogOut", "Account")</li>
                                </ul>
                            </li>
                        </ul>
                    }
                    <h5 class="header-title hidden-xs">
                        <img src="~/Images/ico_evento_top.svg" /> @ViewBag.Title
                    </h5>
                </div>
            </nav>
        </header>
        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <h5 class="header-title hidden">
                    <img src="~/Images/ico_evento_top.svg" /> @ViewBag.Title
                </h5>
                <div class="row">
                    @if (erroPerfis)
                    {
                        <p class="text-danger"><strong>Não foi possivel carregar os perfis, voce está usando o perfil BACKOFFICE</strong> </p>
                    }
                    @RenderBody()
                </div>
                <footer>
                   
                    @* <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>*@
                </footer>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->
    -
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/Site/common/util.js"></script>
    <script src="~/Scripts/Site/iterative.js"></script>
    <script src="~/Scripts/jquery.mask.js"></script>
    @RenderSection("scripts", required: false)

    <script>
        $(document).ready(function () {
            $('.money').mask('000.000.000.000.000,00', { reverse: true, placeholder: "R$ 9.999,99" });
            $('.cpf').mask('000.000.000-00', { reverse: true, placeholder: "999.999.999-99" });
            $('.cnpj').mask('00.000.000/0000-00', { reverse: true, placeholder: "99.999.999/9999-99" });
            $('.cep').mask('00000-000', { placeholder: "99999-999" });
            $('.number').mask('000000000000000000000000000', { reverse: true });
            $('.telefone').mask("(00) 0000-0000");
            $('.celular').mask("(00) 00000-0000");
            $('.hora').mask("99:99", { placeholder: "12:00" });
            $('.data').mask("99/99/9999", placeholder = "99/99/9999");
        });
    </script>

</body>
</html>

HzCasting.WebApp/Views/Shared/_LayoutModelo.cshtml
<!DOCTYPE html>
<html lang="@CultureHelper.GetCurrentNeutralCulture()">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")   
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", required: false)

    <script src="https://use.fontawesome.com/53052d2b92.js"></script>


</head>
<body>
    <div id="wrapper">
        <!-- Sidebar -->       
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">                     
                <li class="sidebar-brand">
                    <a href="#">
                        <img src="~/Images/logo_hz_sistema.svg" />                        
                    </a>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i><img src="~/Images/ico_modelo_menu.svg" /></i>@Resources.Inicio</a>
                    <ul class="dropdown-custom dropdown-menu" role="menu" aria-labelledby="dLabel">
                        <li>@Html.ActionLink(Resources.Perfil, "Perfil", "Modelo")</li>
                        <li>@Html.ActionLink(Resources.Album, "Album", "Modelo")</li>
                        <li>@Html.ActionLink(Resources.Notificacao, "Notificacao", "Modelo")</li>                        
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i><img src="~/Images/ico_modelo_menu.svg" /></i>@Resources.Convites</a>
                    <ul class="dropdown-custom dropdown-menu" role="menu" aria-labelledby="dLabel">
                        <li>@Html.ActionLink(Resources.Pendentes, "Pendentes", "Invite")</li>
                        <li>@Html.ActionLink(Resources.Aceitos, "Aceitos", "Invite")</li>
                        <li>@Html.ActionLink(Resources.Rejeitados, "Rejeitados", "Invite")</li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i><img src="~/Images/ico_modelo_menu.svg" /></i>@Resources.Agenda</a>
                    <ul class="dropdown-custom dropdown-menu" role="menu" aria-labelledby="dLabel">
                        <li>@Html.ActionLink(Resources.Casting, "CastingModelo", "Casting")</li>
                        <li>@Html.ActionLink(Resources.Eventos, "EventosModelo", "Evento")</li> 
                    </ul>
                </li>    
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i><img src="~/Images/ico_modelo_menu.svg" /></i>@Resources.Idioma</a>
                    <ul class="dropdown-custom dropdown-menu" role="menu" aria-labelledby="dLabel">
                        <li>@Html.ActionLink(Resources.Portugues, "SetCulture", new { culture = "pt-BR", returnUrl = this.Request.RawUrl }, null)</li>
                        <li>@Html.ActionLink(Resources.Ingles, "SetCulture", new { culture = "en", returnUrl = this.Request.RawUrl }, null)</li>
                    </ul>                                        
                </li>                                            
            </ul>                     
        </div>
        <!-- /#sidebar-wrapper -->
        <!--Page Header-->
       <header class="header">
           <nav class="navbar navbar-default">
               <div class="container-fluid">
                   <!-- Brand and toggle get grouped for better mobile display -->
                   <div class="navbar-header">
                       <a href="#menu-toggle" class="menu-toggle-btn" id="menu-toggle">
                           <i class="fa fa-bars" aria-hidden="true"></i>
                       </a>                       
                   </div>

                   <ul class="nav navbar-nav navbar-right pull-right">
                       <li class="dropdown">
                           <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                               <span class="hidden-xs">Joana Lewiskin </span>
                               <i class="fa fa-chevron-down" aria-hidden="true"></i>
                           </a>
                           <ul class="dropdown-menu">
                               <li><a href="#">Action</a></li>
                               <li><a href="#">Another action</a></li>
                               <li><a href="#">Something else here</a></li>
                               <li role="separator" class="divider"></li>
                               <li><a href="#">Separated link</a></li>
                           </ul>
                       </li>
                   </ul>
                   <h5 class="header-title hidden-xs">
                       <img src="~/Images/ico_evento_top.svg" /> @ViewBag.Title
                   </h5>
               </div>
           </nav>
       </header>
        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <h5 class="header-title hidden-lg">
                    <img src="~/Images/ico_evento_top.svg" /> @ViewBag.Title
                </h5>
                <div class="row">
                    @RenderBody()
                </div>
                <footer>
                    @* <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>*@
                </footer>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")    
    <script src="~/Scripts/Site/common/util.js"></script>
    @RenderSection("scripts", required: false)

</body>
</html>