HzCasting.WebApp/Models/CastingViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HzCasting.WebApp.Models
{
    public sealed class CastingViewModel
    {
        public Int64? Id { get; set; }
        public Int64 IdEvento { get; set; }
        [Display(Name = "TituloEvento", ResourceType = typeof(Resources.Resources))]
        public String TituloEvento { get; set; }

        public Int64 IdCliente { get; set; }
        [Display(Name = "NomeCliente", ResourceType = typeof(Resources.Resources))]
        public String NomeCliente { get; set; }

        public Int64? IdAgencia { get; set; }
        [Display(Name = "NomeAgencia", ResourceType = typeof(Resources.Resources))]
        public String NomeAgencia { get; set; }

        public HttpPostedFileBase Imagem { get; set; }
        public String ImagemSrc { get; set; }
        //public DateTime? DataInicioCasting { get; set; }

        public Int32? Status { get; set; }
        public Boolean Cliente { get; set; }
        #region Agenda
        public IList<AgendaViewModel> Agendas { get; set; }
        #endregion

    }
}

HzCasting.WebApp/Controllers/AgendaController.cs
using System;
using System.Web.Mvc;
using HzCasting.WebApp.Controllers.Base;
using HzCasting.WebApp.Models;
using HzCasting.Domain.Entities;
using HzCasting.Domain.Interfaces.Application;
using System.Collections.Generic;
using HzCasting.Infra.Common;
using System.Diagnostics;
using System.Linq;

namespace HzCasting.WebApp.Controllers
{

    public class AgendaController : BaseController
    {
        #region fields

        private readonly IAgendaCastingApplication _agendaApplication;
        private readonly ICastingApplication _castingApplication;
        private readonly IPerfilFiltroApplication _perfilFiltroApplication;

        #endregion
        public AgendaController(IAgendaCastingApplication agendaApplication, ICastingApplication castingApplication, IPerfilFiltroApplication perfilFiltroApplication)
        {
            _perfilFiltroApplication = perfilFiltroApplication;
            _agendaApplication = agendaApplication;
            _castingApplication = castingApplication;
        }

        public ActionResult Cadastrar(Int32 idCasting)
        {
            try
            {
                //CarregarSelects();
                var vm = new AgendaViewModel();
                vm.CastingId = idCasting;
                return View(vm);

            }
            catch (Exception)
            {

                return View();

            }
        }

        [HttpPost]
        public ActionResult Cadastrar(AgendaViewModel dadosTela)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View(dadosTela);

                var model = ToModel(dadosTela);
                _agendaApplication.Registrar(model);
                var casting = _castingApplication.Obter(dadosTela.CastingId);
                casting.Agendas = casting.Agendas ?? new List<AgendaCasting>();
                casting.Agendas.Add(model);

                _castingApplication.Atualizar(casting);

                return RedirectToActionPermanent("AgendaPorCasting", "Casting", new { castingId = dadosTela.CastingId });
            }
            catch (Exception ex)
            {
                var vm = dadosTela;
                vm.CastingId = dadosTela.CastingId;
                ModelState.AddModelError("", "Erro interno do servidor");
                return View(vm);
            }
        }


        public JsonResult ListarPorCasting(Int32 castingId)
        {
            try
            {
                var agendas = _castingApplication.Obter(castingId)?.Agendas?
                    .Select(m => new
                    {
                        id = m.Id,
                        dataInicio = m.DataHoraInicio.ToString(),
                        dataFim = m.DataHoraFim.ToString()
                    });

                return Json(agendas, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                Debug.WriteLine("Errro" + ex);
                return Json(new { error = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        private AgendaCasting ToModel(AgendaViewModel dadosTela)
        {

            var dataFim = new DateTime(dadosTela.DataInicio.Value.Year, dadosTela.DataInicio.Value.Month, dadosTela.DataInicio.Value.Day,dadosTela.HoraFim.Value.Hour,dadosTela.HoraFim.Value.Minute,0);
            //dataFim.AddHours(dadosTela.HoraFim.Value.Hour);
            //dataFim.AddSeconds(dadosTela.HoraFim.Value.Second);

            var dataInicio = new DateTime(dadosTela.DataInicio.Value.Year, dadosTela.DataInicio.Value.Month, dadosTela.DataInicio.Value.Day, dadosTela.HoraInicio.Value.Hour, dadosTela.HoraInicio.Value.Minute, 0);
            //dataInicio.AddHours(dadosTela.HoraInicio.Value.Hour);
            //dataInicio.AddSeconds(dadosTela.HoraInicio.Value.Second);


	  return new AgendaCasting {
		DataHoraFim = dataFim,
		DataHoraInicio = dataInicio,
		Endereco = new Endereco {
		  Cep = new Cep {
			Bairro = dadosTela.Bairro,
			CepNumero = dadosTela.Cep,
			Cidade = dadosTela.Cidade,
			Estado = dadosTela.Estado,
			GDE = dadosTela.GDE,
			Logradouro = dadosTela.Logradouro,
			UF = (UfEnum)dadosTela.Uf,
			Zona = dadosTela.Zona

		  },
		  Complemento = dadosTela.Complemento,
		  Numero = dadosTela.Numero
		},
		QuantidadeCandidatos = dadosTela.QuantidadeCandidatos.Value

                //ListaPerfilCasting = new List<PerfilFiltro>
                //{
                //    new PerfilFiltro
                //    {
                //        Castings = new List<Casting >
                //        {
                //            casting
                //        }
                //    }
                //}


            };
        }

        private static IList<AgendaViewModel> ToAgendaViewModel(IList<AgendaCasting> dadosView)
        {
            var modelVws = new List<AgendaViewModel>();

            foreach (var item in dadosView)
            {

                var modelVw = new AgendaViewModel
                {
                    DataInicio = item.DataHoraInicio.Date,
                    HoraInicio = item.DataHoraInicio.Date,
                    HoraFim = item.DataHoraFim.Date,
                    AgendaCastingId = item.Id

                };

                modelVws.Add(modelVw);
            }

            return modelVws;
        }


        // POST: Modelo/Create
        private void CarregarSelects(AgendaCasting agenda = null)
        {

            var uf = default(UfEnum).ToSelectListItem(agenda?.Endereco?.Cep?.UF);


            ViewBag.Uf = uf;

        }
    }
}

HzCasting.WebApp/Controllers/CastingController.cs
using HzCasting.Domain.Entities;
using HzCasting.Domain.Interfaces.Application;
using HzCasting.Infra.Common;
using HzCasting.WebApp.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace HzCasting.WebApp.Controllers
{
    public class CastingController : Base.BaseController
    {
        private readonly IClienteApplication _clienteApplication;
        private readonly IEventoApplication _eventoApplication;
        private readonly ICastingAgendaCastingApplication _agendaCastingApplication;
        private readonly ICastingApplication _castingApplication;
        private readonly IAgenciaApplication _agenciaApplication;
        private readonly IPerfilFiltroApplication _perfilApplication;
        private readonly IInviteApplication _inviteApplication;
        private readonly IUsuarioClienteApplication _usuarioClienteApplication;

        public CastingController(IClienteApplication clienteApplication,
                                 IEventoApplication eventoApplication,
                                 ICastingAgendaCastingApplication agendaCastingApplication,
                                 ICastingApplication castingApplication,
                                 IAgenciaApplication agenciaApplication,
                                 IPerfilFiltroApplication perfilApplication,
                                 IInviteApplication inviteApplication,
                                 IUsuarioClienteApplication usuarioClienteApplication)
        {
            _inviteApplication = inviteApplication;
            _clienteApplication = clienteApplication;
            _eventoApplication = eventoApplication;
            _agendaCastingApplication = agendaCastingApplication;
            _castingApplication = castingApplication;
            _agenciaApplication = agenciaApplication;
            _perfilApplication = perfilApplication;
            _usuarioClienteApplication = usuarioClienteApplication;
        }

        [HttpGet]
        public ViewResult Listar(String titulo, String cliente, String agencia, DateTime? dataFim, DateTime? dataInicio, Int32? statusId, bool? criadoCliente)
        {
            try
            {
                CarregarSelects();

                var casting = _castingApplication.Listar(titulo, cliente, agencia, dataFim, dataInicio, statusId, criadoCliente)

                            .Select(c => new CastingViewModel
                            {
                                Id = c.Id,
                                TituloEvento = c.Evento?.Titulo,
                                NomeCliente = c.Cliente?.RazaoSocial,
                                NomeAgencia = c.Agencia?.Nome,
                                ImagemSrc = c.Foto?.ImagemBinario.GetSrcImage(),
                            }).ToList();

                return View(casting);
            }
            catch (Exception ex)
            {
                Debug.WriteLine($"Erro: {ex}");
                var casting = new List<CastingViewModel>();
                return View(casting);
            }
        }

        [HttpGet]
        public ViewResult ListarPorCliente(String titulo, DateTime? dataFim, DateTime? dataInicio)
        {
            try
            {
                var usuarioId = User.Identity.GetUserId();

                var usuarioCliente = _usuarioClienteApplication.Obter(x => x.IdUsuario == usuarioId).FirstOrDefault();


                var casting = _castingApplication.Obter(x => x.Cliente.Id == usuarioCliente.ClienteId);
                var itens = casting.Select(c => new CastingViewModel
                            {
                                Id = c.Id,
                                TituloEvento = c.Evento?.Titulo,
                                ImagemSrc = c.Foto?.ImagemBinario.GetSrcImage()
                            }).ToList();

                return View(itens);
            }
            catch (Exception ex)
            {
                Debug.WriteLine($"Erro: {ex}");
                var casting = new List<CastingViewModel>();
                return View(casting);
            }
        }

        [HttpGet]
        public ActionResult Cadastrar()
        {
            CarregarSelects();
            return View();
        }

        [HttpGet]
        public ActionResult CastingModelo()
        {
            var userId = User.Identity.GetUserId();

            var roles = ObterRoles();

            var castings =
            ToCastingViewModel(
                _inviteApplication.Obter(
                                            i => (i.Booking.Modelo.IdUsuario == userId || roles.Contains("admin")) &&
                                            i.StatusTrackInvite == StatusTrackInviteEnum.Aceito &&
                                            i.Booking.StatusModeloCastingEnum == StatusModeloCastingEnum.Aprovada)
                                        .Select(
                                                    i => i.Booking.PerfilFiltro.Casting

                                        ).ToList()
            );

            return View(castings);
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            var casting = _castingApplication.Obter(id);

            return View();
        }

        [HttpGet]
        public ActionResult CadastrarPorCliente()
        {
            CarregarSelects();
            return View();
        }

        [HttpGet]
        public ActionResult AgendaPorCasting(int castingId)
        {
            List<Casting> castingVm = new List<Casting>();

            try
            {

                var casting = _castingApplication.Obter(castingId);

                castingVm.Add(casting);


                return View(ToCastingViewModel(castingVm));

            }
            catch (Exception ex)
            {
                Debug.WriteLine("Errro" + ex);
                return Json(new { error = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }


        [HttpPost]
        public ActionResult CadastrarPorCliente(CastingViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View(model);

                var usuarioId = User.Identity.GetUserId();

                var usuarioCliente = _usuarioClienteApplication.Obter(x => x.IdUsuario == usuarioId).FirstOrDefault();

                if (usuarioCliente != null)
                {
                    _castingApplication.Registrar(usuarioCliente.ClienteId, model.IdEvento, model.Imagem);

                    return RedirectToAction("ListarPorCliente");
                }

                return Json(new { erro = "Erro ao cadastrar Casting !" });
            }
            catch (Exception ex)
            {
                Debug.Write($"Erro: {ex}");
                return Json(new { erro = "Erro ao cadastrar Casting !" });

            }
        }



        [HttpPost]
        public ActionResult Cadastrar(CastingViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View(model);

                _castingApplication.Registrar(model.IdCliente, model.IdEvento, model.Imagem, model.IdAgencia);

                return RedirectToAction("Listar");
            }
            catch (Exception ex)
            {
                Debug.Write($"Erro: {ex}");
                return Json(new { erro = "Erro ao cadastrar Casting !" });

            }
        }

        public ActionResult Editar(Int32 id, Boolean cliente = false)
        {
            var casting = _castingApplication.Obter(id);
            var vm = ToCastingViewModel(casting);
            vm.Cliente = cliente;
            return View(vm);
        }
        [HttpPost]
        public ActionResult Editar(CastingViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View(model);

                if (model.Cliente)
                {
                    var usuarioId = User.Identity.GetUserId();
                    var usuarioCliente = _usuarioClienteApplication.Obter(x => x.IdUsuario == usuarioId).FirstOrDefault();
                    if (usuarioCliente == null) throw new ApplicationException("Usuario não encontrado");

                    _castingApplication.Registrar(usuarioCliente.ClienteId, model.IdEvento, model.Imagem);
                    return RedirectToAction("ListarPorCliente");
                }

                _castingApplication.Atualizar(model.IdCliente, model.IdEvento, model.Imagem, model.IdAgencia, model.Id);
                return RedirectToAction("Listar");
            }
            catch (Exception ex)
            {
                Debug.Write($"Erro: {ex}");
                return Json(new { erro = "Erro ao cadastrar Casting !" });

            }
        }

        private void CarregarSelects(CastingAgendaCasting casting = null)
        {
            var uf = default(UfEnum).ToSelectListItem();
            ViewBag.Uf = uf;

            var statusCasting = default(StatusCastingEnum).ToSelectListItem();
            ViewBag.StatusCasting = statusCasting;
        }

        [HttpGet]
        public async Task<JsonResult> CarregarAutoCompleteAgencia()
        {
            try
            {
                var agencias = await Task.FromResult(_agenciaApplication.Listar());
                var jsonAgencias = agencias.Select(m => new
                {
                    nome = m.Nome,
                    id = m.Id
                });
                return Json(jsonAgencias, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex);
                return Json(new { error = "Erro, contate o suporte!" });
            }
        }

        [HttpGet]
        public async Task<JsonResult> CarregarAutoCompleteCliente()

HzCasting.WebApp/Views/Casting/AgendaPorCasting.cshtml
@model IEnumerable<HzCasting.WebApp.Models.CastingViewModel>

@{
    ViewBag.Title = Resources.AgendaPorCasting;
}


@foreach (var casting in Model)
{

    <h5 class="page-title">
        @*@Resources.ListarCastingCadastrados*@
        @Html.ActionLink(Resources.AdicionarAgendaCasting, "Cadastrar", "Agenda", new { idCasting = casting.Id }, new { @class = "btn btn-primary pull-right" })
    </h5>


    <div class="container-content-block">
        <div class="table-responsive">
            <table class="table table-hover">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Agendas.FirstOrDefault().DataInicio)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Agendas.FirstOrDefault().HoraInicio)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Agendas.FirstOrDefault().HoraFim)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Agendas.FirstOrDefault().QuantidadeCandidatos)
                    </th>
                    @*<th>
                            @Html.DisplayName(@Resources.Acoes)
                        </th>*@
                </tr>
                @foreach (var agenda in casting.Agendas)
                {

                    <tr>
                        <td>
                            @agenda.DataInicio.Value.ToShortDateString()
                        </td>
                        <td>
                            @agenda.HoraInicio.Value.ToShortTimeString()
                        </td>
                        <td>
                            @agenda.HoraFim.Value.ToShortTimeString()
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => agenda.QuantidadeCandidatos)
                        </td>
                        @*<td class="actions">
                                <a href="@Url.Action("Cadastrar", "Agenda", new { id = item.CastingId })"><i class="fa fa-plus text-danger" aria-hidden="true"></i></a>
                            </td>*@
                    </tr>
                }
            </table>
        </div>
    </div>

}

HzCasting.WebApp/Views/Casting/Cadastrar.cshtml
@model HzCasting.WebApp.Models.CastingViewModel

@{
    ViewBag.Title = Resources.CadastrarCasting;

}

@*<h5 class="page-title">Informe os dados solicitados abaixo para cadastrar um novo evento. Os campos com <span class="text-danger">*</span> são obrigatórios.</h5>*@
<h5 class="page-title">@Resources.CamposObrigatorios</h5>

@section styles{
    <link href="~/Content/typehead.css" rel="stylesheet" />
}


<div class="form-content-block no-margin-bottom">
    <h1 class="block-title">@Resources.DadosCasting</h1>
</div>
<div class="form-content-block no-margin-top">

    @using (Html.BeginForm("Cadastrar", "Casting", FormMethod.Post, new { @enctype = "multipart/form-data", @id = "form-casting" }))
    {
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Partial("~/Views/Casting/_FormCasting.cshtml")
        
        <!--<div class="form-group">
            <label class="control-label col-md-2">UPLOAD DE IMAGEM DO CASTING</label>
            <div class="col-md-10">
                <img id="imagem-icon" src="http://camaleon.tuzitio.com/assets/camaleon_cms/image-not-found-4a963b95bf081c3ea02923dceaeb3f8085e1a654fc54840aac61a57a60903fef.png" class="img-thumbnail image" alt="" />
                <input type="file" id="ImagemEvento" name="Imagem" style="display: none;" accept="images" />
            </div>
        </div>-->

        <div class="form-group col-md-12">
            <input id="btnSalvar" type="submit" value="@Resources.Salvar" class="btn btn-danger" />
            @*<input type="button" value="Booking" class="btn btn-dark" />*@
            <a href="~/Perfil/Cadastrar" class="btn btn-dark">Booking</a>
        </div>
    }

</div>










@*<div class="row">

        <h1 class="text-danger">AGENDA</h1>
        <form id="formAgenda">
            <div class="form-horizontal">
                <div class="form-group">
                    <label class="control-label col-md-2">DATA *</label>
                    <div class="col-md-10">
                        <input type="date" value="" id="DataInicio" class="form-control" required="required" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">HORÁRIO INICIO *</label>
                    <div class="col-md-10">
                        <input type="time" value="" id="HoraInicio" class="form-control" required="required" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">HORÁRIO FIM</label>
                    <div class="col-md-10">
                        <input type="time" value="" id="HoraFim" class="form-control" required="required" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">PERFIL</label>
                    <div class="col-md-10">
                        <select id="PerfilId" class="form-control" required="required">
                            <option value="1"> Selecione o perfil</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">LOCAL *</label>
                    <div class="col-md-10">
                        <input type="text" value="" id="Local" class="form-control" required="required" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">CEP *</label>
                    <div class="col-md-10">
                        <input type="text" value="" id="Cep" class="form-control" required="required" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">CIDADE *</label>
                    <div class="col-md-10">
                        <input type="text" value="" id="Cidade" class="form-control" required="required" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">UF</label>
                    <div class="col-md-10">
                        @Html.DropDownList("Uf", ViewBag.Uf as IEnumerable<SelectListItem>, new { @class = "form-control", @required = "required" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">BAIRRO *</label>
                    <div class="col-md-10">
                        <input type="text" value="" id="Bairro" class="form-control" required="required" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">LOGRADOURO *</label>
                    <div class="col-md-10">
                        <input type="text" value="" id="Logradouro" class="form-control" required="required" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">N° *</label>
                    <div class="col-md-10">
                        <input type="number" value="" id="Numero" class="form-control" required="required" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">COMPLEMENTO *</label>
                    <div class="col-md-10">
                        <input type="text" value="" id="Complemento" class="form-control" required="required" />
                    </div>
                </div>
                <button class="btn btn-danger pull-right" type="submit" id="btnAdicionar">Adicionar</button>
            </div>
        </form>

    </div>*@

@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @*<script src="~/Scripts/jquery.maskedinput.min.js"></script>*@
    <script src="~/Scripts/typehead.min.js"></script>
    <script src="~/Scripts/Site/casting/casting.js"></script>

}

HzCasting.WebApp/Views/Casting/CastingModelo.cshtml
@model IEnumerable<HzCasting.WebApp.Models.CastingViewModel>

@{
    ViewBag.Title = Resources.CastingModelo;
    //Layout = "~/Views/Shared/_LayoutModelo.cshtml";
}

<div class="container-content-block">
    <div class="table-responsive">
        <table class="table table-hover">
            <tr>                
                <th>
                    @Html.DisplayNameFor(model => model.TituloEvento)
                </th>                
                <th>
                    @Html.DisplayNameFor(model => model.NomeCliente)
                </th>               
                <th>
                    @Html.DisplayNameFor(model => model.NomeAgencia)
                </th>
                <th>
                    @Html.DisplayName(@Resources.Acoes)
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>                   
                    <td>
                        @Html.DisplayFor(modelItem => item.TituloEvento)
                    </td>                    
                    <td>
                        @Html.DisplayFor(modelItem => item.NomeCliente)
                    </td>                    
                    <td>
                        @Html.DisplayFor(modelItem => item.NomeAgencia)
                    </td>
                    <td class="actions">
                        <a href="@Url.Action("Details", "Casting", new { id = item.Id })"><i class="fa fa-search-plus text-danger" aria-hidden="true"></i></a>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

HzCasting.WebApp/Views/Casting/Details.cshtml
@model HzCasting.WebApp.Models.CastingViewModel

@{
    ViewBag.Title = "Details";
    //Layout = "~/Views/Shared/_LayoutModelo.cshtml";
}

<div class="container-content-block">
    <div class="table-responsive">
        <table class="table table-hover">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.TituloEvento)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NomeCliente)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NomeAgencia)
                </th>
            </tr>
            <tr>
                <td>
                    @Html.DisplayFor(model => model.TituloEvento)
                </td>
                <td>
                    @Html.DisplayFor(model => model.NomeCliente)
                </td>
                <td>
                    @Html.DisplayFor(model => model.NomeAgencia)
                </td>
            </tr>
        </table>
    </div>
</div>

HzCasting.WebApp/Views/Casting/Editar.cshtml
@model HzCasting.WebApp.Models.CastingViewModel

@{
    ViewBag.Title = Resources.Editar;
}

<h5 class="page-title">@Resources.CamposObrigatorios</h5>

@section styles{
    <link href="~/Content/typehead.css" rel="stylesheet" />
}


<div class="form-content-block no-margin-bottom">
    <h1 class="block-title">@Resources.DadosCasting</h1>
</div>
<div class="form-content-block no-margin-top">

    @using (Html.BeginForm("Editar", "Casting", FormMethod.Post, new { @enctype = "multipart/form-data", @id = "form-casting" }))
    {
        @Html.HiddenFor(m => m.TituloEvento, new { @id = "nomeTituloDefault" })
        @Html.HiddenFor(m => m.NomeCliente, new { @id = "nomeClienteDefault"})
        @Html.HiddenFor(m => m.NomeAgencia, new { @id = "nomeAgenciaDefault" })
        @Html.HiddenFor(m => m.Id)
        @Html.HiddenFor(m => m.Cliente)
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Partial("~/Views/Casting/_FormCasting.cshtml")


        <div class="form-group col-md-12">
            <input id="btnSalvar" type="submit" value="@Resources.Salvar" class="btn btn-danger" />
            <a href="~/Perfil/Cadastrar" class="btn btn-dark">Booking</a>
        </div>
    }

</div>


@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/typehead.min.js"></script>
    <script src="~/Scripts/Site/casting/casting.js"></script>

}

HzCasting.WebApp/Views/Casting/_FormCasting.cshtml
@model HzCasting.WebApp.Models.CastingViewModel
 
<div class="form-group col-md-4">
    <label class="typelabel">@Resources.NomeEvento</label>
    <input type="text" name="TituloEvento" value="" id="NomeEvento" class="typeahead" placeholder="Digite o nome do evento" required="required" />
    <input type="hidden" value="" name="IdEvento" />
</div>

<div class="form-group col-md-4">
    <label class="typelabel">@Resources.NomeCliente</label>
    <input type="text" value="" id="NomeCliente" class="typeahead" name="NomeCliente" placeholder="Digite o nome do cliente" required="required" />
    <input type="hidden" value="" name="IdCliente" />
</div>

<div class="form-group col-md-4">
    <label class="typelabel">@Resources.NomeAgencia</label>
    <input type="text" name="NomeAgencia" value="" id="NomeAgencia" class="typeahead" placeholder="Digite o nome da Agencia" required="required" />
    <input type="hidden" value="" name="IdAgencia" />
</div>

<div class="clearfix"></div>

@if(Model?.ImagemSrc != null)
{
    <img src="@Model.ImagemSrc" alt="imagem evento" width="200"/>
}
<div class="form-group col-md-12">
    <label for="fotoEvento">@Resources.UploadFotos</label>
    <label for="fotoEvento" class="upload-custom">
        <label class="center-content-upload">
            <input type="file" name="Imagem" id="ImagemEvento" />
            <label for="ImagemEvento" class="content-upload">
                <i class="fa fa-times-circle" aria-hidden="true"></i>
                <span>@Resources.CliqueParaAdicionarFoto</span>
            </label>
        </label>
    </label>
</div>