HzCasting.WebApp/Models/Modelos/ModeloCaracteristicasViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HzCasting.WebApp.Models.Modelos
{
    public sealed class ModeloCaracteristicasViewModel
    {
        public int ModeloId { get; set; }
        public int AlturaPerfiModelo { get; set; }
        public int BustoPerfiModelo { get; set; }
        public int CalcadoPerfiModelo { get; set; }
        public int CinturaPerfiModelo { get; set; }
        public int CorCabeloPerfilModelo { get; set; }
        public int CorOlhosPerfiModelo { get; set; }
        public int CorPelePerfiModelo { get; set; }
        public decimal ManequimPerfiModelo { get; set; }
        public string OutrosPerfiModelo { get; set; }
        public int PesoPerfiModelo { get; set; }
        public int QuadrilPerfiModelo { get; set; }
        public int CategoriaModelo { get; set; }
        public int TipoModelo { get; set; }
        public DateTime DataAprovacao { get; set; }
    }
}

HzCasting.WebApp/Models/Modelos/ModeloContatoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HzCasting.WebApp.Models.Modelos
{
    public sealed class ModeloContatoViewModel
    {
        public string UsuarioId { get; set; }
        public int ModeloId { get; set; }
        public string CelularDadosPessoais { get; set; }
        public string TelefoneDadosPessoais { get; set; }
    }
}

HzCasting.WebApp/Models/Modelos/ModeloDadosBancariosViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HzCasting.WebApp.Models.Modelos
{
    public sealed class ModeloDadosBancariosViewModel
    {
        public int ModeloId { get; set; }
        public string AgenciaBanco { get; set; }
        public string ContaBanco { get; set; }
        public string NomeBanco { get; set; }
        public int TipoContaBanco { get; set; }
    }
}

HzCasting.WebApp/Models/Modelos/ModeloDadosCadastraisViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HzCasting.WebApp.Models.Modelos
{
    public sealed class ModeloDadosCadastraisViewModel
    {
        public string UsuarioId { get; set; }

        public int ModeloId { get; set; }

        [Required]
        public string PrimeiroNomeDadosPessoais { get; set; }

        [Required]
        public string UltimoNomeDadosPessoais { get; set; }

        [Required]
        public DateTime DataNascimentoDadosPessoais { get; set; }

        public int EstadoCivilId { get; set; }

        public int SexoId { get; set; }
    }
}

HzCasting.WebApp/Models/Modelos/ModeloDadosComplementaresViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HzCasting.WebApp.Models.Modelos
{
    public sealed class ModeloDadosComplementaresViewModel
    {
        public int ModeloId { get; set; }
        public bool DisponibilidadeHorario { get; set; }
        public bool DisponibilidadeViagem { get; set; }
        public bool PossuiVeiculo { get; set; } 
    }
}

HzCasting.WebApp/Models/Modelos/ModeloDocumentoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HzCasting.WebApp.Models.Modelos
{
    public sealed class ModeloDocumentoViewModel
    {
        public int ModeloId { get; set; }
        public string PisDocumento { get; set; }
        public string RgDocumento { get; set; }
        public string CateiraProfissionalDocumento { get; set; }
        public string Cpf { get; set; }
    }
}

HzCasting.WebApp/Models/Modelos/ModeloEnderecoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HzCasting.WebApp.Models.Modelos
{
    public sealed class ModeloEnderecoViewModel
    {
        public string UsuarioId { get; set; }
        public int ModeloId { get; set; }
        public string CidadeEndereco { get; set; }
        public string EstadoEndereco { get; set; }
        public string LogradouroEndereco { get; set; }
        public string BairroEndereco { get; set; }
        public string CepEndereco { get; set; }
        public string GDEEndereco { get; set; }
        public int UfEndereco { get; set; }
        public string ZonaEndereco { get; set; }
        public string ComplementoEndereco { get; set; }
        public string NumeroEndereco { get; set; }
    }
}

HzCasting.WebApp/Models/Modelos/ModeloEscolaridadeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HzCasting.WebApp.Models.Modelos
{
    public sealed class ModeloEscolaridadeViewModel
    {
        public int ModeloId { get; set; }
        public Int32? EscolaridadeId { get; set; }
        //public string FormacaoEscolaridade { get; set; }
        //public string SuperiorEscolaridade { get; set; }
        //public string TecnicoEscolaridade { get; set; }
    }
}

HzCasting.WebApp/Models/Modelos/ModeloFotoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HzCasting.WebApp.Models.Modelos
{
    public sealed class ModeloFotoViewModel
    {
        public HttpPostedFileBase Imagem { get; set; }
        public Int32 IdUsuario { get; set; }
    }
}

HzCasting.WebApp/Models/Modelos/ModeloIdiomaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HzCasting.WebApp.Models.Modelos
{
    public sealed class ModeloIdiomaViewModel
    {
        public int ModeloId { get; set; }
        public string DescricaoIdioma { get; set; }
        public List<IdiomasViewModel> Idiomas { get; set; }
    }

    public sealed class IdiomasViewModel
    {
        public int IdiomaId { get; set; }
    }
}

HzCasting.WebApp/Models/Modelos/ModeloUsuarioViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HzCasting.WebApp.Models.Modelos {
  public class ModeloUsuarioViewModel {

	private const string MENSAGEM_CAMPO_OBRIGATORIO = "Campo obrigatorio";

	public string UsuarioId { get; set; }
	[Required]
	public string Email { get; set; }

	[Required]
	public string Cpf { get; set; }

	[Required(ErrorMessage = MENSAGEM_CAMPO_OBRIGATORIO)]
	[StringLength(100, ErrorMessage = "O {0} deve ser de pelo menos {2} caracteres.", MinimumLength = 6)]
	[DataType(DataType.Password)]
	[Display(Name = "Password", ResourceType = typeof(Resources.Resources))]
	public string Password { get; set; }

	[Required(ErrorMessage = MENSAGEM_CAMPO_OBRIGATORIO)]
	[DataType(DataType.Password)]
	[Display(Name = "ConfirmPassword", ResourceType = typeof(Resources.Resources))]
	[Compare("Password", ErrorMessage = "A Senha e a confirmação não coincidem")]
	public string ConfirmPassword { get; set; }
  }
}

HzCasting.WebApp/Controllers/ModeloController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Diagnostics;
using HzCasting.WebApp.Controllers.Base;
using HzCasting.WebApp.Models;
using HzCasting.WebApp.Models.Modelos;
using HzCasting.Domain.Entities;
using HzCasting.Domain.Interfaces.Application;
using HzCasting.WebApp.ModelsView;
using System.Collections.Generic;
using HzCasting.Infra.Common;
using Microsoft.AspNet.Identity.Owin;

namespace HzCasting.WebApp.Controllers
{

    public class ModeloController : BaseController
    {
        #region fields
        private readonly ModeloCadastrarViewModel _viewModel;
        private readonly IModeloApplication _modeloApplication;
        private readonly IUsuarioApplication _usuario;
        private readonly IEnderecoApplication _enderecoApplication;
        private readonly ICastingApplication _castingApplication;
        private readonly IIdiomaApplication _idiomaApplication;

        #endregion

        public ModeloController(IModeloApplication modeloApplication, IUsuarioApplication usuario,
            IEnderecoApplication enderecoApplication, ICastingApplication castingApplication, IIdiomaApplication idiomaApplication)
        {
            _modeloApplication = modeloApplication;
            _usuario = usuario;
            _castingApplication = castingApplication;
            _enderecoApplication = enderecoApplication;
            _idiomaApplication = idiomaApplication;
            _viewModel = new ModeloCadastrarViewModel();


        }

        public ActionResult ImportarFotosModelo(Int32 idModelo = 0, Int32 take = 10, Int32 skip = 0)
        {
            var id = string.Empty;
            Modelo modelo;
            var vm = new ImportacaoFotosViewModel();
            var isBackOffice = idModelo != 0;
            vm.BackOffice = isBackOffice;
            try
            {
                if (isBackOffice)
                {
                    modelo = _modeloApplication.Obter(idModelo);
                    id = modelo?.IdUsuario;
                }
                else
                {
                    id = User.Identity.GetUserId();
                    modelo = _modeloApplication.Obter(m => m.IdUsuario == id)?.FirstOrDefault();
                }

                vm.UsuarioId = id;
                return View(vm);
            }
            catch (ApplicationException ex)
            {

                ModelState.AddModelError("", ex.Message);
                return View(vm);
            }
            catch (Exception ex)
            {
                Debug.WriteLine("Erro:" + ex);
                ModelState.AddModelError("", ex.Message);
                return View(vm);
            }

        }

        public ActionResult ListarFotos(Int32 idModelo = 0)
        {
            var idUsuario = string.Empty;
            var isBackOffice = idModelo != 0;
            ViewBag.IsBackOffice = isBackOffice;
            try
            {
                if (isBackOffice)
                {
                    var modelo = _modeloApplication.Obter(idModelo);
                    idUsuario = modelo?.IdUsuario;
                }
                else
                {
                    idUsuario = User.Identity.GetUserId();
                }
                ViewBag.UsuarioId = idUsuario;
                return View();
            }
            catch (ApplicationException ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
            catch (Exception ex)
            {
                Debug.WriteLine("Erro:" + ex);
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        [HttpPost]
        public async Task<JsonResult> CarregarFotosFacebookModelo(String idUsuario, Int32 take = 10, Int32 skip = 0)
        {
            try
            {
                var user = await UserManager.FindByIdAsync(idUsuario);
                if (user == null) throw new ApplicationException("Usuário não encontrado!");

                var fotos = new List<UsuarioFacebook>();
                IEnumerable<FacebookViewModel> vm;
                try
                {
                    fotos = await _usuario.ObterFotosUsuarioAsync(user.FacebookToken, take, skip);
                }
                catch (ApplicationException ex)
                {
                    //caso nao tenham fotos associadas, nao exibe.
                    Debug.WriteLine("Modelo sem facebook", ex.Message);
                }

                vm = fotos.Select(m => new FacebookViewModel()
                {
                    Id = m.Id,
                    ImageURL = m.ImageURL

                });

                return Json(vm, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { error = ex.Message });
            }
        }

        [HttpPost]
        public JsonResult CarregarFotosModelo(String idUsuario, Int32 take = 10, Int32 skip = 0)
        {

            var fotos = new List<FotoModelo>();
            try
            {
                if (string.IsNullOrEmpty(idUsuario))
                    return Json(new { error = "Id do usuario nao informado ou incorreto!" });

                fotos = _modeloApplication
                                            .Obter(m => m.IdUsuario == idUsuario)?
                                            .FirstOrDefault()?
                                            .Fotos?
                                            .Take(take)
                                            .Skip(skip)
                                            .ToList();

                var vm = fotos?.Select(MapearFotosModelo)?.ToList();
                var itens = new
                {
                    data = vm ?? new List<FacebookViewModel>(),
                    quantidadePendentes = vm?.Select(m => m.Status == StatusFotoModeloEnum.Pendente.ToString())?.Count() ?? 0
                };

                var json = Json(itens, JsonRequestBehavior.AllowGet);
                json.MaxJsonLength = int.MaxValue;
                return json;
            }
            catch (ApplicationException ex)
            {
                ModelState.AddModelError("", ex.Message);
                var vm = new List<FacebookViewModel>();
                return Json(new { error = ex.Message }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Debug.WriteLine("Erro:" + ex);

                return Json(new { error = ex.Message });
            }

        }

        [HttpPost]
        public JsonResult RemoverFoto(String usuarioId, Int64 idFoto)
        {
            try
            {
                _modeloApplication.RemoverFoto(usuarioId, idFoto);
                return Json(new { });
            }
            catch (Exception ex)
            {
                Debug.WriteLine("Erro:" + ex);

                return Json(new { error = ex.Message });
            }
        }

        [HttpPost]
        public JsonResult AlterarFoto(String usuarioId, Int64 idFoto)
        {
            try
            {
                _modeloApplication.AlterarFotoPrincipal(usuarioId, idFoto);
                return Json(new { });
            }
            catch (Exception ex)
            {
                Debug.WriteLine("Erro:" + ex);

                return Json(new { error = ex.Message });
            }
        }

        [HttpPost]
        public JsonResult AprovarFoto(String usuarioId, Int32 idFoto)
        {
            try
            {
                _modeloApplication.AprovarFoto(usuarioId, idFoto);
                return Json(new { });
            }
            catch (Exception ex)
            {
                Debug.WriteLine("Erro:" + ex);

                return Json(new { error = ex.Message });
            }
        }
        public ActionResult CriarPerfilModelo(int modeloId)
        {
            var modelo = _modeloApplication.Obter(modeloId);

            var mainModel = ToMainModel(modelo);

            return View(mainModel);
        }

        [HttpPost]
        public ActionResult CriarPerfilModelo(ModeloPerfilMainViewModel model)
        {
            var domain = ToMainDomain(model);

            _modeloApplication.Atualizar(domain);

            var mainModel = ToMainModel(domain);

            return View(mainModel);
        }

        [HttpPost]
        public JsonResult CadastrarIdioma(ModeloIdiomaViewModel model)
        {
            var modelo = _modeloApplication.Obter(model.ModeloId);

            modelo.Idiomas.Clear();

            foreach (var item in model.Idiomas)
            {
                modelo.Idiomas.Add(new ModeloIdioma()
                {
                    ModeloId = model.ModeloId,
                    IdiomaId = item.IdiomaId
                });
            }

            _modeloApplication.Atualizar(modelo);

            return Json(true);
        }

        private ModeloPerfilMainViewModel ToMainModel(Modelo modelo)
        {
            var vm = new ModeloPerfilMainViewModel();

            if (modelo.PerfilModelo != null)
            {
                vm.Caracteristicas.Altura = modelo.PerfilModelo.Altura;
                vm.Caracteristicas.Busto = modelo.PerfilModelo.Busto;
                vm.Caracteristicas.Calcado = modelo.PerfilModelo.Calcado;
                vm.Caracteristicas.Cintura = modelo.PerfilModelo.Cintura;
                vm.Caracteristicas.Manequim = modelo.PerfilModelo.Manequim;
                vm.Caracteristicas.Outros = modelo.PerfilModelo.Outros;
                vm.Caracteristicas.Peso = modelo.PerfilModelo.Peso;
                vm.Caracteristicas.CorCabeloId = (CorCabeloEnum)modelo.PerfilModelo.CorCabelo;
                vm.Caracteristicas.CorOlhosId = modelo.PerfilModelo.CorOlhos;
                vm.Caracteristicas.CorPeleId = modelo.PerfilModelo.CorPele;

HzCasting.WebApp/Views/Modelo/AgendaEventos.cshtml
@{
    ViewBag.Title = Resources.Eventos;
    //Layout = "~/Views/Shared/_LayoutModelo.cshtml";
}

HzCasting.WebApp/Views/Modelo/Cadastrar.cshtml
@model HzCasting.WebApp.Models.Modelos.ModeloBaseViewModel

@{
    ViewBag.Title = Resources.CadastrarModelo;
}


@Html.Partial("~/Views/Modelo/_FormModelo.cshtml")

<input type="hidden" id="userId" />
<input type="hidden" id="modeloId" />

<div class="form-group col-md-2"> 
    <div class="text-danger">
        @Html.ValidationMessage("error")
    </div>
</div>

<div class="clearfix"></div>
@*<div class="col-md-12">
        <i class="fa fa-long-arrow-left" aria-hidden="true"></i>
        @Html.ActionLink("Back to List", "Index")
    </div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/Site/modelo/cadastrar.js"></script>
    <script src="~/Scripts/Site/modelo/modelo.js"></script>
}

HzCasting.WebApp/Views/Modelo/HomeModelo.cshtml
@{
    ViewBag.Title = "HomeModelo";
    //Layout = "~/Views/Shared/_LayoutModelo.cshtml";
}

<h2>HomeModelo</h2>

HzCasting.WebApp/Views/Modelo/ImportarFotosModelo.cshtml
@model HzCasting.WebApp.Models.ImportacaoFotosViewModel
@{
    ViewBag.Title = "Galeria";
    var usuarioId = Model.UsuarioId;
    var backOffice = Model.BackOffice;
}
@section styles {
    <style>
        img.img-thumbnail {
            width: 15%;
        }
    </style>
}
<input type="hidden" id="usuarioId" value="@usuarioId" />
<a href="/Modelo/ListarFotos" class="btn  btn-primary  pull-right">Ver fotos selecionadas</a>
@Html.ActionLink("Voltar á edição do perfil", "Editar", "Modelo", new { id = usuarioId }, new { @class = "btn btn-primary" })


<div class="container" id="loading" style="display:none;">
    <button class="btn btn-lg btn-warning">
        <span class="glyphicon glyphicon-refresh glyphicon-refresh-animate"></span> Carregando...
    </button>
</div>
<br />
<br />
<br />
@if (!backOffice)
{

    @Html.ValidationMessage("", new { @class = "text-danger" })
    <div class="row">


        <input type="file" id="arquivo-file" value="" />
        <br />
        <button class="btn btn-success" id="btnSalvar">@Resources.GravarImagensSelecionadas</button>
        <output id="saida-gravar-imagem"></output>
    </div>
} 
    <div id="content">

    </div>
    <div id="page-selection" style="display:none;"></div>

    @section scripts {
        <script src="~/Scripts/Site/fotosModelo/fotosModelo.js"></script>
        <script src="~/Scripts/jquery.bootpag.min.js"></script>
        <script src="~/Scripts/Site/importarFotosModelo/importarFotosModelo.js"></script>
    }

HzCasting.WebApp/Views/Modelo/Index.cshtml
@*@model IEnumerable<HzCasting.WebApp.Models.FacebookViewModel>

@{
    ViewBag.Title = "Index";
}
@section styles {
    <style>
        img.img-thumbnail {
            width: 15%;
        }
    </style>

}
@section scripts {


    <script src="~/Scripts/Site/fotosModelo/fotosModelo.js"></script>
}
<div class="row">
    <input type="file" id="arquivo-file" value="" />
    <button class="btn btn-success" id="btnSalvar">@Resources.GravarImagensSelecionadas</button>
    <output id="saida-gravar-imagem"></output>
</div>
<div class="row">


    @foreach (var item in Model)
    {

        <text>
            <img src="@item.ImageURL" class="img-thumbnail" name="img-selection" />
        </text>
    }
</div>*@

HzCasting.WebApp/Views/Modelo/Listar.cshtml
@model IEnumerable<HzCasting.WebApp.Models.Modelos.ModeloBaseViewModel>

@{
    ViewBag.Title = Resources.ListarModelo;
}

<h5 class="page-title">
    @*Veja a baixo a lista de modelos cadastrados no sistema.<br />Aqui você pode cadastrar novos modelos, editá-los e excluí-los quando necessário.*@
    @Resources.ListarModelosCadastrados
    <a class="btn btn-primary pull-right" href="Cadastrar">@Resources.Cadastrar</a>
</h5>

<div class="form-content-block">
    <form action="/Modelo/Listar">
        <div class="row">

            <div class="form-group col-xs-12 col-md-3">
                <label>@Resources.Nome</label>
                <input type="text" name="nome" class="form-control" />
            </div>

            <div class="form-group col-xs-12 col-md-3">
                <label>@Resources.RgDocumento</label>
                <input type="text" name="rg" class="form-control" />
            </div>

            <div class="form-group col-xs-12 col-md-3">
                <label>CPF</label>
                <input type="text" name="cpf" class="form-control cpf" />
            </div>

            <div class="form-group col-xs-6 col-md-2">
                <div class="row">
                    <label for="DataNascimento" class="control-label col-xs-12 col-md-12">@Resources.DataNascimentoDadosPessoais</label>
                    <div class="col-xs-12 col-md-12">
                        <div class="input-group">
                            <input type="text" id="DataNascimento" name="DataNascimento" class="form-control dataNascimento data" , placeholder="99/99/9999" />
                            <span class="input-group-addon"><i class="fa fa-calendar" aria-hidden="true"></i></span>
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-group col-xs-12 col-md-5">
                <div class="row">
                    <label class="col-xs-12 col-md-12"> </label>
                    <div class="col-xs-6 col-md-3">
                        <button class="btn btn-dark btn-block" type="submit">@Resources.Filtrar</button>
                    </div>
                    <div class="col-xs-6 col-md-3">
                        <button class="btn btn-white btn-block">@Resources.Limpar</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<div class="container-content-block">
    <div class="table-responsive">
        <table class="table table-hover">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.PrimeiroNomeDadosPessoais)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UltimoNomeDadosPessoais)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DataNascimentoDadosPessoais)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RgDocumento)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PisDocumento)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CateiraProfissionalDocumento)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cpf)
                </th>

                <th>
                    @Html.DisplayName(@Resources.Acoes)
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.PrimeiroNomeDadosPessoais)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UltimoNomeDadosPessoais)
                    </td>
                    <td>
                        @item.DataNascimentoDadosPessoais.GetValueOrDefault().ToShortDateString()
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RgDocumento)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PisDocumento)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CateiraProfissionalDocumento)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cpf)
                    </td>
                    <td class="actions">
                        <a href="@Url.Action("Editar", "Modelo", new { id = item.ModeloId })"><i class="fa fa-pencil-square-o text-danger" aria-hidden="true"></i></a>
                        <a href="@Url.Action("Deletar", "Modelo", new { id = item.ModeloId })"><i class="fa fa-trash text-danger" aria-hidden="true"></i></a>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

HzCasting.WebApp/Views/Modelo/ListarFotos.cshtml
@{
    ViewBag.Title = "Listar Fotos";
    var usuarioId = ViewBag.UsuarioId;
    var IsBackOffice = ViewBag.IsBackOffice ?? false;
}
@section styles {
    <style>
        img.img-thumbnail {
            width: 15%;
        }
        .hide {
            display:none;
        }
    </style>

}
<input type="hidden" id="usuarioId" value="@usuarioId" />
@if (IsBackOffice)
{
    <input type="hidden" id="modelo" value="@(IsBackOffice)" />

}

@if (!IsBackOffice)
{
    <a href="/Modelo/ImportarFotosModelo" class="btn  btn-primary  pull-right">Importar Mais fotos</a>
    @Html.ActionLink("Voltar á edição do perfil", "Editar", "Modelo", new { id = usuarioId }, new { @class = "btn btn-primary" })
}
<div class="container hide" id="loading">
    <button class="btn btn-lg btn-warning">
        <span class="glyphicon glyphicon-refresh glyphicon-refresh-animate"></span> Carregando...
    </button>
</div>
<br />
<br />

<h4 class="hide" id="quantidadeItens">Quantidade de fotos pendentes: <span id="quantidadePendentes"></span></h4>
<div id="content">
</div>
<div id="page-selection"></div>

@section scripts {
    <script src="~/Scripts/jquery.bootpag.min.js"></script>
    <script src="~/Scripts/Site/listarFotosModelo/listarFotosModelo.js"></script>
}

HzCasting.WebApp/Views/Modelo/ModeloComposite.cshtml
@{
    ViewBag.Title = "ModeloComposite";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("_ModeloComposite")

HzCasting.WebApp/Views/Modelo/NoRadar.cshtml
@{
    ViewBag.Title = Resources.NoRadar;
    //Layout = "~/Views/Shared/_LayoutModelo.cshtml";
}

HzCasting.WebApp/Views/Modelo/_ModelosSelecionadasCasting.cshtml
@model IEnumerable<HzCasting.WebApp.Models.ModelosSelecionadasViewModel>



<div class="container-content-block">
    <div class="table-responsive">


        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Foto</th>
                    <th>@Html.DisplayNameFor(x => x.NomeModelo)</th> 
                    @*<th>Detalhe</th>*@
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <img src="@item.ImagemSrc ?? @Url.Content("~/Images/ft_usuario_padrao.jpg")" alt="Foto Modelo" />
                        </td>
                        <td>@item.NomeModelo</td>

                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>